apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-imageupdater 

resources:
- https://raw.githubusercontent.com/argoproj-labs/argocd-image-updater/master/manifests/install.yaml
- namespace.yaml