apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- github.com/argoproj/argo-cd//manifests/cluster-install?ref=v2.1.5

resources:
- namespace.yaml

namespace: argocd

patchesStrategicMerge:
- argocd-server.yaml    # allow HTTP until we have things setup.

# additional resources like ingress rules, cluster and repository secrets.
# resources:
# - clusters-secrets.yaml
# - repos-secrets.yaml

# # changes to config maps
# patchesStrategicMerge:
# - overlays/argo-cd-cm.yaml