apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-events

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-events/v1.5.0/manifests/namespace-install.yaml
  - https://raw.githubusercontent.com/argoproj/argo-events/v1.5.0/examples/eventbus/native.yaml
