apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

resources:
- IngressLetsEncrypt.yaml
- Issuer.yaml

namespace: argocd

patchesStrategicMerge:
- argocd-server.yaml  

# additional resources like ingress rules, cluster and repository secrets.
# resources:
# - clusters-secrets.yaml
# - repos-secrets.yaml

# # changes to config maps
# patchesStrategicMerge:
# - overlays/argo-cd-cm.yaml