apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production 
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: rscottwatson@gmail.com
    privateKeySecretRef:
      name: letsencrypt-production 
    solvers:
    # An empty 'selector' means that this solver matches all domains
    - selector: {}
      http01:
        ingress:
          class: nginx