apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: tooling
  source:
    path: argo-apps/argo-cd/overlays/production
    repoURL: https://github.com/rscottwatson/argo-demo 
    targetRevision: develop
  destination:
    namespace: argocd 
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    # syncOptions:
    #   - CreateNamespace=true