apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: tooling
  source:
    path: argo-apps/argo-events/base
    repoURL: https://github.com/rscottwatson/argo-demo 
    targetRevision: develop
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true